openapi: 3.0.0
servers:
  - url: "https://emela.org/sushi"
info:
  description: "A microservice to select one random item from the list of items."
  version: "0.0.1"
  title: "Sushi Random Picker"
  contact:
    url: 'http://emela.org'
    email: "info@emela.org"

paths:
  '/items':
    post:
      summary: "saves list of items"
      description: "This endpoint saves the list of items."
      operationId: "saveItems"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemDetailRequest'
      responses:
        '200':
          description: "successful operation"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '401':
          description: 'Unauthorized, Invalid or Missing Access Token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '403':
          description: 'Access Denied, Insufficient Scope privilege Or Expired Access Token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        default:
          description: Server Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
    get:
      summary: "retrieves one item randomly"
      description: "This endpoint randomly picks one item from the list"
      operationId: "retrieveItem"
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemDetailResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '401':
          description: 'Unauthorized, Invalid or Missing Access Token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '403':
          description: 'Access Denied, Insufficient Scope privilege Or Expired Access Token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        default:
          description: Server Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

components:
  schemas:
    ErrorModel:
      type: object
      properties:
        developerMessage:
          type: string
          description: >-
            Verbose, plain language description of the problem for the app
            developer with hints about how to fix it.
        userMessage:
          type: string
          description: Pass this message on to the app user if needed
        errorCode:
          type: string
          description: Error code defined for the error
        moreInfo:
          type: string
          description: Any additional information on the error (e.g. website links)
    ItemDetailRequest:
      type: object
      required:
        - item-id
        - items
      properties:
        item-id:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    ItemDetailResponse:
      type: object
      required:
        - item-id
        - item
      properties:
        item-id:
          type: string
        item:
          $ref: '#/components/schemas/Item'
    Item:
      type: object
      required:
        - name
      properties:
        name:
          type: string

externalDocs:
  description: "Find out more about Sushi Random Picker"
  url: "http://emela.org/sushi"